export const PERMISSIONS = {
  EVENT_CREATE: 'EVENT_CREATE',
  EVENT_VIEW: 'EVENT_VIEW',
  EVENT_UPDATE: 'EVENT_UPDATE',
  EVENT_DELETE: 'EVENT_DELETE',

  TRACK_CREATE: 'TRACK_CREATE',
  TRACK_VIEW: 'TRACK_VIEW',
  TRACK_UPDATE: 'TRACK_UPDATE',
  TRACK_DELETE: 'TRACK_DELETE',

  WORKSHOP_CREATE: 'WORKSHOP_CREATE',
  WORKSHOP_VIEW: 'WORKSHOP_VIEW',
  WORKSHOP_UPDATE: 'WORKSHOP_UPDATE',
  WORKSHOP_DELETE: 'WORKSHOP_DELETE',

  TEAM_CREATE: 'TEAM_CREATE',
  TEAM_VIEW: 'TEAM_VIEW',
  TEAM_UPDATE: 'TEAM_UPDATE',
  TEAM_DELETE: 'TEAM_DELETE',

  PARTICIPANT_VIEW: 'PARTICIPANT_VIEW',
  PARTICIPANT_APPROVE: 'PARTICIPANT_APPROVE',

  USER_CREATE: 'USER_CREATE',
  USER_VIEW: 'USER_VIEW',
  USER_UPDATE: 'USER_UPDATE',
  USER_ROLE_ASSIGN: 'USER_ROLE_ASSIGN',

  JUDGING_ASSIGN: 'JUDGING_ASSIGN',
  SCORE_CREATE: 'SCORE_CREATE',
  SCORE_VIEW: 'SCORE_VIEW',

  GITHUB_CONFIGURE: 'GITHUB_CONFIGURE',
  GITHUB_REPOSITORY_CREATE: 'GITHUB_REPOSITORY_CREATE',
  GITHUB_ACCESS_REVOKE: 'GITHUB_ACCESS_REVOKE',

  AI_REVIEW_TRIGGER: 'AI_REVIEW_TRIGGER',
  AI_REVIEW_VIEW: 'AI_REVIEW_VIEW',

  RESULT_PUBLISH: 'RESULT_PUBLISH',

  AUDIT_LOG_VIEW: 'AUDIT_LOG_VIEW',

  SYSTEM_CONFIG_MANAGE: 'SYSTEM_CONFIG_MANAGE'
}

export const ALL_PERMISSIONS = Object.values(PERMISSIONS)

export const ROLE_PERMISSION_MAP = {
  ADMIN: ALL_PERMISSIONS,
  EVENT_COORDINATOR: [
    PERMISSIONS.EVENT_CREATE,
    PERMISSIONS.EVENT_VIEW,
    PERMISSIONS.EVENT_UPDATE,
    PERMISSIONS.TRACK_CREATE,
    PERMISSIONS.TRACK_VIEW,
    PERMISSIONS.TRACK_UPDATE,
    PERMISSIONS.TRACK_DELETE,
    PERMISSIONS.WORKSHOP_CREATE,
    PERMISSIONS.WORKSHOP_VIEW,
    PERMISSIONS.WORKSHOP_UPDATE,
    PERMISSIONS.TEAM_VIEW,
    PERMISSIONS.PARTICIPANT_VIEW,
    PERMISSIONS.PARTICIPANT_APPROVE,
    PERMISSIONS.USER_CREATE,
    PERMISSIONS.USER_VIEW,
    PERMISSIONS.USER_UPDATE,
    PERMISSIONS.JUDGING_ASSIGN,
    PERMISSIONS.GITHUB_CONFIGURE,
    PERMISSIONS.GITHUB_REPOSITORY_CREATE,
    PERMISSIONS.GITHUB_ACCESS_REVOKE,
    PERMISSIONS.AI_REVIEW_TRIGGER,
    PERMISSIONS.AI_REVIEW_VIEW,
    PERMISSIONS.RESULT_PUBLISH,
    PERMISSIONS.AUDIT_LOG_VIEW
  ],
  COORDINATOR: [
    PERMISSIONS.EVENT_CREATE,
    PERMISSIONS.EVENT_VIEW,
    PERMISSIONS.EVENT_UPDATE,
    PERMISSIONS.TRACK_CREATE,
    PERMISSIONS.TRACK_VIEW,
    PERMISSIONS.TRACK_UPDATE,
    PERMISSIONS.TRACK_DELETE,
    PERMISSIONS.WORKSHOP_CREATE,
    PERMISSIONS.WORKSHOP_VIEW,
    PERMISSIONS.WORKSHOP_UPDATE,
    PERMISSIONS.TEAM_VIEW,
    PERMISSIONS.PARTICIPANT_VIEW,
    PERMISSIONS.PARTICIPANT_APPROVE,
    PERMISSIONS.USER_CREATE,
    PERMISSIONS.USER_VIEW,
    PERMISSIONS.USER_UPDATE,
    PERMISSIONS.JUDGING_ASSIGN,
    PERMISSIONS.GITHUB_CONFIGURE,
    PERMISSIONS.GITHUB_REPOSITORY_CREATE,
    PERMISSIONS.GITHUB_ACCESS_REVOKE,
    PERMISSIONS.AI_REVIEW_TRIGGER,
    PERMISSIONS.AI_REVIEW_VIEW,
    PERMISSIONS.RESULT_PUBLISH,
    PERMISSIONS.AUDIT_LOG_VIEW
  ],
  JUDGE: [
    PERMISSIONS.EVENT_VIEW,
    PERMISSIONS.TRACK_VIEW,
    PERMISSIONS.WORKSHOP_VIEW,
    PERMISSIONS.TEAM_VIEW,
    PERMISSIONS.SCORE_CREATE,
    PERMISSIONS.SCORE_VIEW,
    PERMISSIONS.AI_REVIEW_VIEW
  ],
  MENTOR: [
    PERMISSIONS.EVENT_VIEW,
    PERMISSIONS.TRACK_VIEW,
    PERMISSIONS.WORKSHOP_VIEW,
    PERMISSIONS.TEAM_VIEW,
    PERMISSIONS.AI_REVIEW_VIEW
  ],
  USER: [
    PERMISSIONS.EVENT_VIEW,
    PERMISSIONS.TRACK_VIEW,
    PERMISSIONS.WORKSHOP_VIEW,
    PERMISSIONS.TEAM_CREATE,
    PERMISSIONS.TEAM_VIEW
  ],
  PARTICIPANT: [
    PERMISSIONS.EVENT_VIEW,
    PERMISSIONS.TRACK_VIEW,
    PERMISSIONS.WORKSHOP_VIEW,
    PERMISSIONS.TEAM_CREATE,
    PERMISSIONS.TEAM_VIEW
  ]
}
