export const QUEUE_NAMES = {
  GITHUB_PUSH_EVENTS: 'github-push-events'
}

export const JOB_TYPES = {
  PROCESS_GITHUB_PUSH_EVENT: 'PROCESS_GITHUB_PUSH_EVENT',
  FETCH_COMMIT_DIFF: 'FETCH_COMMIT_DIFF',
  HOURLY_REPOSITORY_SCAN: 'HOURLY_REPOSITORY_SCAN',
  RUN_STATIC_ANALYSIS: 'RUN_STATIC_ANALYSIS',
  COMPUTE_IMPACT_SCORE: 'COMPUTE_IMPACT_SCORE',
  RUN_PER_PUSH_AUDIT: 'RUN_PER_PUSH_AUDIT',
  RUN_TEAM_AGGREGATE_AUDIT: 'RUN_TEAM_AGGREGATE_AUDIT'
}
