export const QUEUE_NAMES = {
  GITHUB_PUSH_EVENTS: 'github-push-events'
}

export const JOB_TYPES = {
  PROCESS_GITHUB_PUSH_EVENT: 'PROCESS_GITHUB_PUSH_EVENT',
  RUN_PER_PUSH_AUDIT: 'RUN_PER_PUSH_AUDIT',
  RUN_TEAM_AGGREGATE_AUDIT: 'RUN_TEAM_AGGREGATE_AUDIT'
}
